/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ams;
import java.sql.Connection;
//import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ejiga Samuel
 */
public class Add_Teacher extends javax.swing.JFrame {

    /**
     * Creates new form Add_Teacher
     */
    public Add_Teacher() {
        initComponents();
    }
    
    private void retrieve()
    {
     DefaultTableModel dm = new DBUpdaterT().getData();

        vteach.setModel(dm);
    }
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet result = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teachNamel = new javax.swing.JLabel();
        courseIdL = new javax.swing.JLabel();
        usernameL = new javax.swing.JLabel();
        passkeyL = new javax.swing.JLabel();
        teacherName = new javax.swing.JTextField();
        courseId = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        vteach = new javax.swing.JTable();
        bReturn = new javax.swing.JButton();
        adTeach = new javax.swing.JButton();
        adTeachT = new javax.swing.JLabel();
        buDel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        teachNamel.setText("Name:");

        courseIdL.setText("Courrse:");

        usernameL.setText("Username:");

        passkeyL.setText("Password:");

        vteach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Course", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vteach);

        bReturn.setText("Back");
        bReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReturnActionPerformed(evt);
            }
        });

        adTeach.setText("Add");
        adTeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adTeachActionPerformed(evt);
            }
        });

        adTeachT.setText("Add Teacher");

        buDel.setText("Delete");
        buDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usernameL)
                                .addComponent(courseIdL))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(username)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(courseId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(passkeyL)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(adTeach)
                                .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(teachNamel)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adTeachT)
                            .addComponent(teacherName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buDel)
                .addGap(28, 28, 28)
                .addComponent(bReturn)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(adTeachT)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teachNamel)
                            .addComponent(teacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(courseIdL)
                            .addComponent(courseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameL)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passkeyL)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bReturn)
                    .addComponent(adTeach)
                    .addComponent(buDel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void adTeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adTeachActionPerformed
        // Collecting input from text field to create login details and teacher details
        // Login details
        try {
            con = Connection1.connectDB();
            String sql = "insert into login (username, password, usertype) values(?,?,?)";
            pst = con.prepareStatement(sql);
            String id = username.getText();
            String pass = password.getText();
            String type = "Teacher";
            pst.setString(1,id);
            pst.setString(2, pass);
            pst.setString(3,"Teacher");
            //System.out.println(""+id + "  " + pass);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Saved in login");
   
        } catch (Exception e ) {
            System.out.println("no");
            JOptionPane.showMessageDialog(null, e);

        }
         //Teacher details
         try {
            con = Connection1.connectDB();
            String sql = "insert into teacher (teachername) values(?)";
            pst = con.prepareStatement(sql);
            //String id = teacher.getText();
            String name = teacherName.getText();
            //String user = username.getText();
            //String passkey = password.getText();
            //pst.setString(1,id);
            pst.setString(1, name);
            //pst.setString(2,user);
           // pst.setString(3, passkey);
            //System.out.println(""+id + "  " + pass);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Saved in teacher");
   
        } catch (Exception e ) {
            System.out.println("no");
            JOptionPane.showMessageDialog(null, e);

        }
         populateTable();
    }//GEN-LAST:event_adTeachActionPerformed

    private void populateTable(){
        String sql = "select * from teacher";
        try{
            pst = con.prepareStatement(sql);
            result = pst.executeQuery();
            vteach.setModel(DbUtils.resultSetToTableModel(result));
            
        }catch(SQLException ex){
        JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void bReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReturnActionPerformed
        // TODO add your handling code here:
        Admin f2 = new Admin();
        f2.setVisible(true);
        dispose();
    }//GEN-LAST:event_bReturnActionPerformed

    private void buDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buDelActionPerformed
        // TODO add your handling code here:
        String[] options = {"Yes", "No"};
        int answ = JOptionPane.showOptionDialog(null, "Sure To Delete??", "Delete Confirm", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

        if (answ == 0) {
            int index = vteach.getSelectedRow();
            String id = vteach.getValueAt(index, 0).toString();

            if (new DBUpdaterT().delete(id)) {
                JOptionPane.showMessageDialog(null, "Deleted Updated");

                //CLEAR TXT
                //studNameT.setText("");
                teachNamel.setText("");
                //teamTxt.setText("");

           retrieve();
            } 
            else
            {
                JOptionPane.showMessageDialog(null, "Not Deleted");
            }

        }
    }//GEN-LAST:event_buDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adTeach;
    private javax.swing.JLabel adTeachT;
    private javax.swing.JButton bReturn;
    private javax.swing.JButton buDel;
    private javax.swing.JTextField courseId;
    private javax.swing.JLabel courseIdL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel passkeyL;
    private javax.swing.JTextField password;
    private javax.swing.JLabel teachNamel;
    private javax.swing.JTextField teacherName;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameL;
    private javax.swing.JTable vteach;
    // End of variables declaration//GEN-END:variables
}
