/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ams;
import java.sql.Connection;
//import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ejiga Samuel
 */
public class Add_Course extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet result = null;

    /**
     * Creates new form Add_Course
     */
    public Add_Course() {
        initComponents();
    }
    
    private void retrieve()
    {
     DefaultTableModel dm = new DBUpdater().getData();

        vTable.setModel(dm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CourseNt = new javax.swing.JLabel();
        CourseIdT = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vTable = new javax.swing.JTable();
        courseName = new javax.swing.JTextField();
        courseId = new javax.swing.JTextField();
        bReturnc = new javax.swing.JButton();
        addCourse = new javax.swing.JButton();
        adCorseT = new javax.swing.JLabel();
        buDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CourseNt.setText("Course Name:");

        CourseIdT.setText("Course Code:");

        vTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course Name", "Course code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vTable);

        courseId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseIdActionPerformed(evt);
            }
        });

        bReturnc.setText("Back");
        bReturnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReturncActionPerformed(evt);
            }
        });

        addCourse.setText("Add");
        addCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseActionPerformed(evt);
            }
        });

        adCorseT.setText("Add Course");

        buDelete.setText("Delete");
        buDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CourseNt)
                    .addComponent(CourseIdT))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courseName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courseId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adCorseT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addCourse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buDelete)
                        .addGap(18, 18, 18)
                        .addComponent(bReturnc)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adCorseT)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CourseNt)
                            .addComponent(courseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CourseIdT)
                            .addComponent(courseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bReturnc)
                    .addComponent(addCourse)
                    .addComponent(buDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void courseIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseIdActionPerformed

    private void bReturncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReturncActionPerformed
        // TODO add your handling code here:
        Admin f2 = new Admin();
        f2.setVisible(true);
        dispose();
    }//GEN-LAST:event_bReturncActionPerformed
    
    private void populateTable(){
        String sql = "select * from course";
        try{
            pst = con.prepareStatement(sql);
            result = pst.executeQuery();
            vTable.setModel(DbUtils.resultSetToTableModel(result));
            
        }catch(SQLException ex){
        JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void addCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseActionPerformed
        // TODO add your handling code here:
        try {
            con = Connection1.connectDB();
            String sql = "insert into course (courseid, coursename) values(?,?)";
            pst = con.prepareStatement(sql);
            String id = courseId.getText();
            String name = courseName.getText();
            pst.setString(1,id);
            pst.setString(2, name);
            //System.out.println(""+id + "  " + pass);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Saved in Course");
   
        } catch (SQLException ex ) {
            System.out.println("no");
            JOptionPane.showMessageDialog(null, ex);

        }
        populateTable();
    }//GEN-LAST:event_addCourseActionPerformed

    //SET SELECTED VALUE TO TEXTFIELDS
    private void vTable1MouseClicked(java.awt.event.MouseEvent evt) {
        String id = vTable.getValueAt(vTable.getSelectedRow(), 1).toString();
        String name = vTable.getValueAt(vTable.getSelectedRow(), 2).toString();
        //String team = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
        CourseIdT.setText(id);
        CourseNt.setText(name);
        //teamTxt.setText(team);

    }
    
    private void buDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buDeleteActionPerformed
        // TODO add your handling code here:
        String[] options = {"Yes", "No"};
        int answ = JOptionPane.showOptionDialog(null, "Sure To Delete??", "Delete Confirm", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

        if (answ == 0) {
            int index = vTable.getSelectedRow();
            String id = vTable.getValueAt(index, 0).toString();

            if (new DBUpdater().delete(id)) {
                JOptionPane.showMessageDialog(null, "Deleted Updated");

                //CLEAR TXT
                CourseIdT.setText("");
                CourseNt.setText("");
                //teamTxt.setText("");

           retrieve();
            } 
            else
            {
                JOptionPane.showMessageDialog(null, "Not Deleted");
            }

        }

    
    }//GEN-LAST:event_buDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CourseIdT;
    private javax.swing.JLabel CourseNt;
    private javax.swing.JLabel adCorseT;
    private javax.swing.JButton addCourse;
    private javax.swing.JButton bReturnc;
    private javax.swing.JButton buDelete;
    private javax.swing.JTextField courseId;
    private javax.swing.JTextField courseName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable vTable;
    // End of variables declaration//GEN-END:variables
}
